var data = [
	{letter: 'A',
	 questions: ['What is Luke Skywalker\'s father first name?', 
	 			 'What planet was first destroyed by the Death Star?',
	 			 'Who is the captain at the corvette that carries Princess Leia?'],
	 answers: ['ANAKIN', 
	 		   'ALDERAAN',
	 		   'ANTILLES'],
	 answered: false
	},
	{letter: 'B',
	 questions: ['What small orange robot is one of the protagonists of The Force Awakens?', 
	 			 'What bountyhunter delivers Han Solo to Jabba the Hutt?',
	 			 'What animal native of Tattoine is usually domesticated to carry around heavy loads?'],
	 answers: ['BB8', 
	 		   'BOBA FETT',
	 		   'BANTHA' ],
	 answered: false
	},
	{letter: 'C',
	 questions: ['What is the capital of the old republic', 
	 			 'Who is R2D2\'s companion',
	 			 'What conflict was carried on between the republic and a separatist movement led by Count Duku'],
	 answers: ['CORUSCANT', 
	 		   'C3PO',
	 		   'CLONE WARS'],
	 answered: false
	},
	{letter: 'D',
	 questions: ['What count turned himself to the dark side', 
	 			 'What title usually preceeds the new name taken by the Sith lords',
	 			 'What is the site of the first base for the Rebel Alliance'],
	 answers: ['DUKU', 
	 		   'DARTH',
	 		   'DANTOOINE'],
	 answered: false
	},
	{letter: 'E',
	 questions: ['What moon is inhabited by Ewoks', 
	 			 'What form of government was implemented by senator Palpatine as a response to the separatist movement.',
	 			 'What was the surname of the female soldier who was key in the Scariff operation.'],
	 answers: ['ENDOR', 
	 		   'EMPIRE',
	 		   'ERSO'],
	 answered: false
	},
	{letter: 'F',
	 questions: ['What entity gives the Jedi their powers', 
	 			 'What radical movement comanded by Supreme Leader Snoke intends to restore the empire',
	 			 'What nickname uses FN-2187 to call himself after defecting the first order where he served as stormtrooper'],
	 answers: ['FORCE', 
	 		   'FIRST ORDER',
	 		   'FINN'],
	 answered: false
	},
	{letter: 'G',
	 questions: ['Who confronts Han Solo in the Tattoine cantina with the intention of bringing him to Jabba the Hutt', 
	 			 'What planet was the location of large factories set by the separatist movement for the production of droids and weapons during the clone wars',
	 			 'What amphibious species inhabits an underwater world in the planet Naboo'],
	 answers: ['GREEDO', 
	 		   'GEONOSIS',
	 		   'GUNGANS'],
	 answered: false
	},
	{letter: 'H',
	 questions: ['What frozen planet was a hidden base for the rebellion for a while', 
	 			 'What famous smuggler became a leader of the rebellion and a general',
	 			 'What famous criminal clan did the infamous Jabba belong to'],
	 answers: ['HOTH', 
	 		   'HAN SOLO',
	 		   'HUTT'],
	 answered: false
	},
	{letter: 'I',
	 questions: ['What war droid that became a bounty hunter answered Darth Vader\'s call to capture the Millennium Falcon', 
	 			 'What kind of ship is used by the empire as transport for short trips between ships or in orbit',
	 			 'What weapon was key during the battle of Hoth to allow rebel ships escape Echo Base through the imperial siege'],
	 answers: ['IG88', 
	 		   'IMPERIAL SHUTTLE',
	 		   'ION CANNON'],
	 answered: false
	},
	{letter: 'J',
	 questions: ['What order of powerful knights were put in charge of defending the republic and keeping peace', 
	 			 'What criminal member of the Hutt clan kept frozen Han Solo on display at his palace',
	 			 'What is Rey\'s home planet where she lives alone as scavenger'],
	 answers: ['JEDI', 
	 		   'JABBA',
	 		   'JAKKU'],
	 answered: false
	},
	{letter: 'K',
	 questions: ['What crystals are a key element in the constructon of lightsabers by the Jedi and Siths?', 
	 			 'What secret planet was the site of a huge facility dedicated to harvesting clone soldiers to build an army for the Republic?',
	 			 'What Ren knight is a leader in the First Order and student of Supreme Leader Snoke?'],
	 answers: ['KYBER', 
	 		   'KAMINO',
	 		   'KYLO REN'],
	 answered: false
	},
	{letter: 'L',
	 questions: ['What princess from Alderaan became one of the greatest leaders in the Rebel Alliance?', 
	 			 'Who is in charge of the mining facilities of Cloud City in the planet Bespin',
	 			 'What is the main weapon used by both Jedi and Siths'],
	 answers: ['LEIA ORGANA', 
	 		   'LANDO CALRISSIAN',
	 		   'LIGHTSABER'],
	 answered: false
	},
	{letter: 'M',
	 questions: ['What corellian freighter, heavily modified, was able to make the Kessel run in less than 12 parsecs?', 
	 			 'What equipment was used by farmers in Tattooine to harvest water?',
	 			 'What Jedi Master was famous by his purple amethyst-bladed lightsaber?'],
	 answers: ['MILLENNIUM FALCON', 
	 		   'MOISTURE VAPORATOR',
	 		   'MACE WINDU'],
	 answered: false
	},
	{letter: 'N',
	 questions: ['Who served Lando Calrissian’s co-pilot aboard the Millennium Falcon during the Battle of Endor?', 
	 			 'What idyllic planet located close to the Outer Rim is the home of former queen and senator Padme Amidala ?',
	 			 'What species are known for running the Space Federation who joined the Separatist movement and started the Clone Wars?'],
	 answers: ['NIEN NUMB', 
	 		   'NABOO',
	 		   'NEIMOIDIAN'],
	 answered: false
	}

]